// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.18.1
// source: trap.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Trap struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Time      *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	VarBinds  *structpb.Struct       `protobuf:"bytes,2,opt,name=var_binds,json=varBinds,proto3" json:"var_binds,omitempty"`
	Address   string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Version   int32                  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	TrapType  int32                  `protobuf:"varint,5,opt,name=trap_type,json=trapType,proto3" json:"trap_type,omitempty"`
	Community string                 `protobuf:"bytes,6,opt,name=community,proto3" json:"community,omitempty"`
	User      string                 `protobuf:"bytes,7,opt,name=user,proto3" json:"user,omitempty"`
	TrapOid   string                 `protobuf:"bytes,8,opt,name=trap_oid,json=trapOid,proto3" json:"trap_oid,omitempty"`
}

func (x *Trap) Reset() {
	*x = Trap{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trap_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Trap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trap) ProtoMessage() {}

func (x *Trap) ProtoReflect() protoreflect.Message {
	mi := &file_trap_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trap.ProtoReflect.Descriptor instead.
func (*Trap) Descriptor() ([]byte, []int) {
	return file_trap_proto_rawDescGZIP(), []int{0}
}

func (x *Trap) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *Trap) GetVarBinds() *structpb.Struct {
	if x != nil {
		return x.VarBinds
	}
	return nil
}

func (x *Trap) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Trap) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Trap) GetTrapType() int32 {
	if x != nil {
		return x.TrapType
	}
	return 0
}

func (x *Trap) GetCommunity() string {
	if x != nil {
		return x.Community
	}
	return ""
}

func (x *Trap) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *Trap) GetTrapOid() string {
	if x != nil {
		return x.TrapOid
	}
	return ""
}

type Stat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Time       *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	Hostname   string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Drops      int64                  `protobuf:"varint,3,opt,name=drops,proto3" json:"drops,omitempty"`
	Received   int64                  `protobuf:"varint,4,opt,name=received,proto3" json:"received,omitempty"`
	NatsErrors int64                  `protobuf:"varint,5,opt,name=nats_errors,json=natsErrors,proto3" json:"nats_errors,omitempty"`
}

func (x *Stat) Reset() {
	*x = Stat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trap_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Stat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stat) ProtoMessage() {}

func (x *Stat) ProtoReflect() protoreflect.Message {
	mi := &file_trap_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stat.ProtoReflect.Descriptor instead.
func (*Stat) Descriptor() ([]byte, []int) {
	return file_trap_proto_rawDescGZIP(), []int{1}
}

func (x *Stat) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *Stat) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Stat) GetDrops() int64 {
	if x != nil {
		return x.Drops
	}
	return 0
}

func (x *Stat) GetReceived() int64 {
	if x != nil {
		return x.Received
	}
	return 0
}

func (x *Stat) GetNatsErrors() int64 {
	if x != nil {
		return x.NatsErrors
	}
	return 0
}

var File_trap_proto protoreflect.FileDescriptor

var file_trap_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x74, 0x72, 0x61, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73, 0x74,
	0x72, 0x75, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8a, 0x02, 0x0a, 0x04,
	0x54, 0x72, 0x61, 0x70, 0x12, 0x2e, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x04,
	0x74, 0x69, 0x6d, 0x65, 0x12, 0x34, 0x0a, 0x09, 0x76, 0x61, 0x72, 0x5f, 0x62, 0x69, 0x6e, 0x64,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74,
	0x52, 0x08, 0x76, 0x61, 0x72, 0x42, 0x69, 0x6e, 0x64, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1b,
	0x0a, 0x09, 0x74, 0x72, 0x61, 0x70, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x08, 0x74, 0x72, 0x61, 0x70, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x63,
	0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65,
	0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x19, 0x0a,
	0x08, 0x74, 0x72, 0x61, 0x70, 0x5f, 0x6f, 0x69, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x74, 0x72, 0x61, 0x70, 0x4f, 0x69, 0x64, 0x22, 0xa5, 0x01, 0x0a, 0x04, 0x53, 0x74, 0x61,
	0x74, 0x12, 0x2e, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x04, 0x74, 0x69, 0x6d,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x64, 0x72, 0x6f, 0x70, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x64, 0x72,
	0x6f, 0x70, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x64, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x64, 0x12,
	0x1f, 0x0a, 0x0b, 0x6e, 0x61, 0x74, 0x73, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x6e, 0x61, 0x74, 0x73, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x73,
	0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_trap_proto_rawDescOnce sync.Once
	file_trap_proto_rawDescData = file_trap_proto_rawDesc
)

func file_trap_proto_rawDescGZIP() []byte {
	file_trap_proto_rawDescOnce.Do(func() {
		file_trap_proto_rawDescData = protoimpl.X.CompressGZIP(file_trap_proto_rawDescData)
	})
	return file_trap_proto_rawDescData
}

var file_trap_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_trap_proto_goTypes = []interface{}{
	(*Trap)(nil),                  // 0: Trap
	(*Stat)(nil),                  // 1: Stat
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
	(*structpb.Struct)(nil),       // 3: google.protobuf.Struct
}
var file_trap_proto_depIdxs = []int32{
	2, // 0: Trap.time:type_name -> google.protobuf.Timestamp
	3, // 1: Trap.var_binds:type_name -> google.protobuf.Struct
	2, // 2: Stat.time:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_trap_proto_init() }
func file_trap_proto_init() {
	if File_trap_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_trap_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Trap); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_trap_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Stat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_trap_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_trap_proto_goTypes,
		DependencyIndexes: file_trap_proto_depIdxs,
		MessageInfos:      file_trap_proto_msgTypes,
	}.Build()
	File_trap_proto = out.File
	file_trap_proto_rawDesc = nil
	file_trap_proto_goTypes = nil
	file_trap_proto_depIdxs = nil
}
